### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nubspixel** [Normynator/roCORD#31]
**Describe the bug**
The server crashed.

**To Reproduce**
No idea.

**Screenshots**
GDB output:
`
No locals.
#19 0x0000000000b29420 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (rocord::http::*)(), rocord::http*> > >::_M_run (this=0x2aa05e0)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/thread:186
No locals.
#20 0x0000000000bf8d9f in execute_native_thread_routine ()
No symbol table info available.
#21 0x00007ffff7bc660a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#22 0x00007ffff562cbbd in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) bt full
#0  0x00007ffff7bcf02f in send () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff21afcd9 in pt_Send () from /lib64/libnspr4.so
No symbol table info available.
#2  0x00007ffff5ec62a7 in nspr_io_send () from /lib64/libcurl.so.4
No symbol table info available.
#3  0x00007ffff2f72dcc in ssl_DefSend () from /lib64/libssl3.so
No symbol table info available.
#4  0x00007ffff2f63ec4 in ssl3_SendRecord () from /lib64/libssl3.so
No symbol table info available.
#5  0x00007ffff2f643de in SSL3_SendAlert () from /lib64/libssl3.so
No symbol table info available.
#6  0x00007ffff2f79721 in ssl_SecureClose () from /lib64/libssl3.so
No symbol table info available.
#7  0x00007ffff5ec7d0f in Curl_nss_close () from /lib64/libcurl.so.4
No symbol table info available.
#8  0x00007ffff5ea3feb in Curl_disconnect () from /lib64/libcurl.so.4
No symbol table info available.
#9  0x00007ffff5ea7a33 in Curl_done () from /lib64/libcurl.so.4
No symbol table info available.
#10 0x00007ffff5eb805d in multi_runsingle () from /lib64/libcurl.so.4
No symbol table info available.
#11 0x00007ffff5eb83b1 in curl_multi_perform () from /lib64/libcurl.so.4
No symbol table info available.
#12 0x00007ffff5eaf623 in curl_easy_perform () from /lib64/libcurl.so.4
No symbol table info available.
#13 0x0000000000b20a26 in rocord::http::request (this=0x2a94570, r=...)
    at /home/rathena/roCORD/src/map/discord/discord_http.cpp:176
        res = CURLE_OK
        auth = "Authorization:Bot "...
        api_url = "https://discordapp.com/api/v6/guilds/490269602073280524/members/@me/nick"
#14 0x0000000000b1fc47 in rocord::http::send_loop (this=0x2a94570)
    at /home/rathena/roCORD/src/map/discord/discord_http.cpp:59
        req = {
          _vptr.http_request = 0xc7bc20 <vtable for rocord::http_request+16>,
          header = 0x5d37560,
          url = "guilds/490269602073280524/members/@me/nick",
          content = "{\"username\":\"Milky~Discord Bot\"}", type = "PATCH"}
        succ = true
        now = {__d = {__r = 1550745097962936148}}
#15 0x0000000000b2446b in std::__invoke_impl<void, void (rocord::http::*)(), rocord::http*>(std::__invoke_memfun_deref, void (rocord::http::*&&)(), rocord::http*&&) (
    __f=<unknown type in /home/rathena/roCORD/map-server, CU 0x9b094b, DIE 0xa30b33>,
    __t=<unknown type in /home/rathena/roCORD/map-server, CU 0x9b094b, DIE 0xa30b41>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/invoke.h:73
No locals.
#16 0x0000000000b227d8 in std::__invoke<void (rocord::http::*)(), rocord::http*>(void (rocord::http::*&&)(), rocord::http*&&) (
    __fn=<unknown type in /home/rathena/roCORD/map-server, CU 0x9b094b, DIE 0xa32965>,
    __args#0=<unknown type in /home/rathena/roCORD/map-server, CU 0x9b094b, DIE 0xa32980>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/invoke.h:95
No locals.
#17 0x0000000000b2955f in std::thread::_Invoker<std::tuple<void (rocord::http::*)(), rocord::http*> >::_M_invoke<0ul, 1ul> (this=0x2aa05e8)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/thread:234
No locals.
#18 0x0000000000b294dd in std::thread::_Invoker<std::tuple<void (rocord::http::*)(), rocord::http*> >::operator() (this=0x2aa05e8)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/thread:243
---Type <return> to continue, or q <return> to quit---
No locals.
#19 0x0000000000b29420 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (rocord::http::*)(), rocord::http*> > >::_M_run (this=0x2aa05e0)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/thread:186
No locals.
#20 0x0000000000bf8d9f in execute_native_thread_routine ()
No symbol table info available.
#21 0x00007ffff7bc660a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#22 0x00007ffff562cbbd in clone () from /lib64/libc.so.6
No symbol table info available.
`

**System(please complete the following information):**
 - OS: Centos 7
 - Version development-branch
 - Git hash 7041cde31988fcb5dec33bc809f2608da8575cbf
 

**Additional context**

**Comment by Normynator** [comment]
In case of SIGPIPE it’s probably OpenSSL trying to write to a closed connection. Not confirmed yet.
