### ISSUE TITLE
GDB Crash backtrace

### ISSUE THREAD

**Issue by Shaktohh** [Normynator/roCORD#36]
Got a crash from GDB, can you help me to find a workaround ?

#17 0x00007ffff7579742 in curl_easy_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
No symbol table info available.
#18 0x000055555596a002 in rocord::http::request(rocord::http_request&) ()
No symbol table info available.
#19 0x000055555596a255 in rocord::http::send_loop() ()
No symbol table info available.
#20 0x00007ffff7481b2f in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#21 0x00007ffff7fa9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737293739776, -9057342916879798521, 140737488345374, 140737488345375, 140737293739776, 140737488346000, 9057357147288547079, 9057360555226476295}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#22 0x00007ffff72e24cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

**Comment by Shaktohh** [comment]
I guess i have the same issue as 
https://github.com/Normynator/roCORD/issues/31 ?
